version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: my_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    container_name: my_redis_new
    restart: always
    ports:
      - "8081:8081"

volumes:
  mongodb_data:
